# Generated by Django 2.2.5 on 2020-02-25 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
