# Generated by Django 2.2.10 on 2020-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200225_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_money', models.FloatField(default=0)),
            ],
        ),
    ]
